on:
  push:
#    tags:
#      - '*'

name: Create Release

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Install thinks to install dependencies
        run: sudo apt-get update && sudo apt-get install python3-setuptools python3-wheel
      - name: Install 'niet'
        run: sudo pip3 install niet
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: |
          docker build \
              --build-arg "munge_version=$( niet munge_version defs.yaml )" \
              --build-arg "slurm_version=$( niet slurm_version defs.yaml )" \
              .
      
