on:
  push:
#    tags:
#      - '*'

name: Create Release

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update 
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: pip3 install niet
      - run: docker --help
