on:
  push:
#    tags:
#      - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update 
      - run: sudo apt-get install python3-setuptools
      - run: pip3 install niet
        
